# Generated by Django 2.1.1 on 2018-09-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='curate.UserProfile'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections_created', to='curate.UserProfile'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='last_modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections_last_modified', to='curate.UserProfile'),
        ),
    ]
