# Generated by Django 2.1.1 on 2018-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0003_auto_20180919_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfigure',
            name='figure_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='construct',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='keyfigure',
            unique_together={('article', 'figure_number')},
        ),
        migrations.AlterUniqueTogether(
            name='statisticalresult',
            unique_together={('study', 'hypothesis')},
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('article', 'study_number')},
        ),
        migrations.AlterUniqueTogether(
            name='variablerelationship',
            unique_together={('hypothesis', 'ind_var', 'dep_var')},
        ),
    ]
