# Generated by Django 2.1.1 on 2018-09-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0004_auto_20180921_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='is_replication',
        ),
    ]
