# Generated by Django 2.1.1 on 2018-09-27 03:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0005_remove_study_is_replication'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='constraints_on_generality',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('ORIGINAL', 'original'), ('REPLICATION', 'replication'), ('REPRODUCIBILITY', 'reanalysis - reproducibility'), ('META_ANALYSIS', 'reanalysis - meta-analysis'), ('META_RESEARCH', 'reanalysis - meta-research'), ('COMMENTARY', 'commentary')], max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='transparency',
            name='url',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
