# Generated by Django 2.1.1 on 2018-09-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0006_auto_20180927_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='preprint_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='reporting_standards_type',
            field=models.CharField(choices=[('BASIC_4_AT_SUBMISSION', 'Basic-4 (at submission; PSCI, 2014)'), ('BASIC_4_RETROACTIVE', 'Basic-4 (retroactive; 2012)'), ('CONSORT_SPI', 'CONSORT-SPI (2018)'), ('CONSORT', 'CONSORT (2010)'), ('JARS', 'JARS (2018)'), ('STROBE', 'STROBE (2007)'), ('ARRIVE', 'ARRIVE (2010)'), ('NATURE_NEUROSCIENCE', 'Nature Neuroscience (2015)'), ('MARS', 'MARS (2018)'), ('PRISMA', 'PRISMA (2009)'), ('PRISMA_P', 'PRISMA-P (2015)')], max_length=255, null=True),
        ),
    ]
