# Generated by Django 2.1.1 on 2018-09-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0007_auto_20180928_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='research_area',
            field=models.CharField(choices=[('SOCIAL_SCIENCE', 'Social Science'), ('MEDICAL_LIFE_SCIENCE', 'Medical/Life Science')], default='SOCIAL_SCIENCE', max_length=255),
        ),
    ]
