# Generated by Django 2.1.1 on 2018-09-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0008_article_research_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_sub_number',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
