# Generated by Django 2.1.1 on 2018-10-07 06:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0009_study_study_sub_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='curate.Journal'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='preprint_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='reporting_standards_type',
            field=models.CharField(blank=True, choices=[('BASIC_4_AT_SUBMISSION', 'Basic-4 (at submission; PSCI, 2014)'), ('BASIC_4_RETROACTIVE', 'Basic-4 (retroactive; 2012)'), ('CONSORT_SPI', 'CONSORT-SPI (2018)'), ('CONSORT', 'CONSORT (2010)'), ('JARS', 'JARS (2018)'), ('STROBE', 'STROBE (2007)'), ('ARRIVE', 'ARRIVE (2010)'), ('NATURE_NEUROSCIENCE', 'Nature Neuroscience (2015)'), ('MARS', 'MARS (2018)'), ('PRISMA', 'PRISMA (2009)'), ('PRISMA_P', 'PRISMA-P (2015)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='study',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='variablerelationship',
            name='hypothesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='curate.Hypothesis'),
        ),
    ]
