# Generated by Django 2.1.1 on 2018-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0010_auto_20181007_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_sub_number',
        ),
        migrations.AlterField(
            model_name='study',
            name='evidence_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='reporting_standards_type',
            field=models.CharField(blank=True, choices=[('BASIC_4_AT_SUBMISSION', 'Basic-4 (at submission; PSCI, 2014)'), ('BASIC_4_RETROACTIVE', 'Basic-4 (retroactive; 2012)'), ('CONSORT_SPI', 'CONSORT-SPI (2018)'), ('CONSORT', 'CONSORT (2010)'), ('JARS', 'JARS (2018)'), ('STROBE', 'STROBE (2007)'), ('ARRIVE', 'ARRIVE (2010)'), ('NATURE_NEUROSCIENCE', 'Nature Neuroscience (2015)'), ('MARS', 'MARS (2018)'), ('PRISMA', 'PRISMA (2009)'), ('PRISMA_P', 'PRISMA-P (2015)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_number',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transparency',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
