# Generated by Django 2.1.1 on 2018-10-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0011_auto_20181007_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedarticle',
            old_name='is_reproducibilty',
            new_name='is_reproducibility',
        ),
        migrations.AlterField(
            model_name='relatedarticle',
            name='original_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_articles', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='relatedarticle',
            name='related_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_to_articles', to='curate.Article'),
        ),
    ]
