# Generated by Django 2.1.1 on 2018-10-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0012_auto_20181007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(default=2018, null=True),
        ),
    ]
