# Generated by Django 2.1.1 on 2018-10-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0013_auto_20181011_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
