# Generated by Django 2.1.1 on 2018-10-15 01:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0014_auto_20181011_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_figures', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curate.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='auxiliary_hypo_evidence',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='method_differences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='rep_outcome_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transparency',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transparencies', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='transparency',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transparencies', to='curate.Study'),
        ),
    ]
