# Generated by Django 2.1.1 on 2018-10-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0015_auto_20181015_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='dep_var_methods',
            field=models.ManyToManyField(related_name='studies_as_dv_method', to='curate.Method'),
        ),
        migrations.AddField(
            model_name='study',
            name='dep_vars',
            field=models.ManyToManyField(related_name='studies_as_dv', to='curate.Construct'),
        ),
        migrations.AddField(
            model_name='study',
            name='ind_var_methods',
            field=models.ManyToManyField(related_name='studies_as_iv_method', to='curate.Method'),
        ),
        migrations.AddField(
            model_name='study',
            name='ind_vars',
            field=models.ManyToManyField(related_name='studies_as_iv', to='curate.Construct'),
        ),
        migrations.AlterField(
            model_name='method',
            name='construct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='curate.Construct'),
        ),
    ]
