# Generated by Django 2.1.1 on 2018-10-23 05:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0016_auto_20181023_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recommended_contet',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='authors', through='curate.ArticleAuthor', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curate.UserProfile'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='constraints_on_generality',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curate.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='dep_var_methods',
            field=models.ManyToManyField(blank=True, related_name='studies_as_dv_method', to='curate.Method'),
        ),
        migrations.AlterField(
            model_name='study',
            name='dep_vars',
            field=models.ManyToManyField(blank=True, related_name='studies_as_dv', to='curate.Construct'),
        ),
        migrations.AlterField(
            model_name='study',
            name='ind_var_methods',
            field=models.ManyToManyField(blank=True, related_name='studies_as_iv_method', to='curate.Method'),
        ),
        migrations.AlterField(
            model_name='study',
            name='ind_vars',
            field=models.ManyToManyField(blank=True, related_name='studies_as_iv', to='curate.Construct'),
        ),
        migrations.AlterField(
            model_name='study',
            name='method_similarity_type',
            field=models.CharField(blank=True, choices=[('EXACT', 'exact'), ('VERY_SIMILAR', 'very similar'), ('SIMILAR', 'similar')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='replication_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curate.Study'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='browsing_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='curation_contributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_interests',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tracked_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
