# Generated by Django 2.1.1 on 2018-12-31 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0019_auto_20181026_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfigure',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_figures', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_figures', to='curate.Study'),
        ),
        migrations.AlterField(
            model_name='transparency',
            name='transparency_type',
            field=models.CharField(choices=[('PREREG', 'prereg'), ('MATERIALS', 'materials'), ('DATA', 'data'), ('CODE', 'code'), ('REPSTD', 'repstd')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='transparency',
            unique_together={('article', 'study', 'transparency_type', 'url')},
        ),
    ]
