# Generated by Django 2.1.1 on 2018-12-31 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0020_auto_20181231_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparency',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transparencies', to='curate.Article'),
        ),
    ]
