# Generated by Django 2.1.7 on 2019-02-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0022_auto_20190218_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_year', models.CharField(blank=True, max_length=255, null=True)),
                ('commentary_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articleauthor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='last_modifier',
        ),
        migrations.RemoveField(
            model_name='hypothesis',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='hypothesis',
            name='studies',
        ),
        migrations.RemoveField(
            model_name='method',
            name='construct',
        ),
        migrations.RemoveField(
            model_name='relatedarticle',
            name='original_article',
        ),
        migrations.RemoveField(
            model_name='relatedarticle',
            name='related_article',
        ),
        migrations.AlterUniqueTogether(
            name='statisticalresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='statisticalresult',
            name='hypothesis',
        ),
        migrations.RemoveField(
            model_name='statisticalresult',
            name='result_graph',
        ),
        migrations.RemoveField(
            model_name='statisticalresult',
            name='study',
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='study',
            name='article',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dep_var_methods',
        ),
        migrations.RemoveField(
            model_name='study',
            name='dep_vars',
        ),
        migrations.RemoveField(
            model_name='study',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='study',
            name='ind_var_methods',
        ),
        migrations.RemoveField(
            model_name='study',
            name='ind_vars',
        ),
        migrations.RemoveField(
            model_name='study',
            name='replication_of',
        ),
        migrations.AlterUniqueTogether(
            name='transparency',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transparency',
            name='article',
        ),
        migrations.RemoveField(
            model_name='transparency',
            name='study',
        ),
        migrations.AlterUniqueTogether(
            name='variablerelationship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='variablerelationship',
            name='dep_var',
        ),
        migrations.RemoveField(
            model_name='variablerelationship',
            name='hypothesis',
        ),
        migrations.RemoveField(
            model_name='variablerelationship',
            name='ind_var',
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='study',
        ),
        migrations.AddField(
            model_name='article',
            name='author_contributions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='competing_interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='funding_sources',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='html_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='in_press',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='number_of_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='original_article_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='original_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_citations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='peer_review_editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='peer_review_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='peer_reviewers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='preprint_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='preprint_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='prereg_protocol_type',
            field=models.CharField(blank=True, choices=[('PREREG_STUDY_DESIGN_ANALYSIS', 'Preregistered study design + analysis'), ('PREREG_STUDY_DESIGN', 'Preregistered study design'), ('REGISTERED_REPORT', 'Registered report')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='prereg_protocol_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='public_code_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='public_data_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='public_study_materials_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='target_effects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='authors', to='curate.Article'),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Construct',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
        migrations.DeleteModel(
            name='Hypothesis',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='RelatedArticle',
        ),
        migrations.DeleteModel(
            name='StatisticalResult',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='Transparency',
        ),
        migrations.DeleteModel(
            name='VariableRelationship',
        ),
        migrations.AddField(
            model_name='commentary',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='curate.Article'),
        ),
    ]
