# Generated by Django 2.1.7 on 2019-02-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0026_auto_20190220_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
