# Generated by Django 2.1.7 on 2019-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0028_auto_20190220_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfigure',
            name='image',
            field=models.ImageField(null=True, upload_to='key_figures/'),
        ),
    ]
