# Generated by Django 2.1.7 on 2019-02-22 06:32

from django.db import migrations
from autoslug import AutoSlugField

def migrate_data_forward(apps, schema_editor):
    Author = apps.get_model('curate', 'Author')
    for instance in Author.objects.all():
        instance.save() # Will trigger slug update


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0030_auto_20190221_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='Author',
            name='slug',
            field=AutoSlugField(
                populate_from = lambda a: ' '.join(
                    [x for x in [a.first_name, a.middle_name, a.last_name] if x is not None]
                ),
                unique=True,
                editable=True,
                null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
    ]
