# Generated by Django 2.1.7 on 2019-02-24 02:31

import autoslug.fields
import curate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0031_auto_20190222_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfigure',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='key_figure_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from=curate.models.populate_slug, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='keyfigure',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='figure_number',
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='is_figure',
        ),
        migrations.RemoveField(
            model_name='keyfigure',
            name='is_table',
        ),
    ]
