# Generated by Django 2.1.7 on 2019-02-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0032_auto_20190224_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfigure',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyfigure',
            name='thumb_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyfigure',
            name='thumb_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyfigure',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='image',
            field=models.ImageField(height_field=models.PositiveIntegerField(default=0), null=True, upload_to='key_figures/', width_field=models.PositiveIntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='thumbnail',
            field=models.ImageField(height_field=models.PositiveIntegerField(default=0), null=True, upload_to='key_figure_thumbnails/', width_field=models.PositiveIntegerField(default=0)),
        ),
    ]
