# Generated by Django 2.1.7 on 2019-02-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0033_auto_20190224_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfigure',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='key_figures/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='thumbnail',
            field=models.ImageField(height_field='thumb_height', null=True, upload_to='key_figure_thumbnails/', width_field='thumb_width'),
        ),
    ]
