# Generated by Django 2.1.7 on 2019-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0034_auto_20190224_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfigure',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='thumb_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='thumb_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='thumbnail',
            field=models.ImageField(height_field='thumb_height', null=True, upload_to='key_figures/', width_field='thumb_width'),
        ),
        migrations.AlterField(
            model_name='keyfigure',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
