# Generated by Django 2.1.7 on 2019-02-26 04:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0037_auto_20190226_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from=models.CharField(blank=True, max_length=255, null=True), unique=True),
        ),
    ]
