# Generated by Django 2.1.7 on 2019-03-14 03:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
        ('curate', '0039_auto_20190307_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invitations.Invitation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True),
        ),
    ]
