# Generated by Django 2.1.7 on 2019-03-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0041_auto_20190326_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
