# Generated by Django 2.1.7 on 2019-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0042_author_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('ORIGINAL', 'original'), ('CONCEPTUAL', 'conceptual'), ('REPLICATION', 'replication'), ('REPRODUCIBILITY', 'reanalysis - reproducibility'), ('META_ANALYSIS', 'reanalysis - meta-analysis'), ('META_RESEARCH', 'reanalysis - meta-research'), ('COMMENTARY', 'commentary')], default='original', max_length=255),
        ),
    ]
