# Generated by Django 2.1.7 on 2019-08-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0043_add_default_for_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransparencyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transparency_type', models.CharField(blank=True, choices=[('DATA', 'Data'), ('CODE', 'Code'), ('MATERIALS', 'Materials'), ('PREREGISTRATION', 'Preregistration')], max_length=255, null=True)),
                ('protected_access', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transparency_urls', to='curate.Article')),
            ],
        ),
    ]
