# Generated by Django 2.1.7 on 2019-08-12 14:36

from django.db import migrations


def move_transparency_fields(apps, schema_editor):
    Article = apps.get_model('curate', 'Article')
    TransparencyURL = apps.get_model('curate', 'TransparencyURL')

    field_map = {
        'prereg_protocol_url': 'PREREGISTRATION',
        'public_code_url': 'CODE',
        'public_data_url': 'DATA',
        'public_study_materials_url': 'MATERIALS',
    }

    transparency_urls = []
    for article in Article.objects.all():
        for (field, type) in field_map.items():
            url = getattr(article, field)
            # Move URL to new TransparencyURL model
            if url:
                transparency_urls.append(
                    TransparencyURL(article=article, transparency_type=type, url=url)
                )

    TransparencyURL.objects.bulk_create(transparency_urls)


def reset_transparency_fields(apps, schema_editor):
    Article = apps.get_model('curate', 'Article')

    field_map = {
        'PREREGISTRATION': 'prereg_protocol_url',
        'CODE': 'public_code_url',
        'DATA': 'public_data_url',
        'MATERIALS': 'public_study_materials_url',
    }

    transparency_urls = []
    for article in Article.objects.all():
        transparency_urls = article.transparency_urls.all()
        # Move all URLs back to the field on the article model
        if transparency_urls:
            for transparency_url in transparency_urls:
                setattr(article, field_map[transparency_url.transparency_type], transparency_url.url)
                article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0044_transparencyurl'),
    ]

    operations = [
        migrations.RunPython(move_transparency_fields, reset_transparency_fields)
    ]
