# Generated by Django 2.1.7 on 2019-08-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0045_move_existing_transparency_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prereg_protocol_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='public_code_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='public_data_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='public_study_materials_url',
        ),
    ]
