# Generated by Django 2.1.7 on 2019-08-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0046_remove_transparency_url_fields_from_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_source_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_coverage', to='curate.Article')),
            ],
        ),
    ]
