# Generated by Django 2.1.7 on 2019-08-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0048_presentation_supplementalmaterials_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='analyses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='analyses_all_details_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='commentary_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='commentary_target_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='conditions_all_details_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='data_nontransparency_reason',
            field=models.CharField(blank=True, choices=[('PROP', 'Proprietary/IP'), ('ETHI', 'Ethical reasons')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='disclosure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='excluded_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='excluded_data_all_details_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='materials_nontransparency_reason',
            field=models.CharField(blank=True, choices=[('PROP', 'Proprietary/IP'), ('ETHI', 'Ethical reasons')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='other_disclosures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='other_disclosures_all_details_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='reproducibility_original_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reproducibility_original_study_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sample_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sample_size_all_details_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='under_peer_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='unreported_studies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='unreported_studies_all_details_reported',
            field=models.BooleanField(default=False),
        ),
    ]
