# Generated by Django 2.1.7 on 2019-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0050_add_basic_4_7_retroactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='outcomes_all_details_reported',
            field=models.BooleanField(default=False),
        ),
    ]
