# Generated by Django 2.1.7 on 2019-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0052_add_default_reporting_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disclosure_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
