# Generated by Django 2.1.7 on 2019-09-11 09:27

from django.db import migrations


def update_reporting_standard(apps, schema_editor):
    # Change any existing BASIC_4_7_RETROACTIVE articles to the new BASIC_4_7_RETROACTIVE
    Article = apps.get_model('curate', 'Article')
    for article in Article.objects.filter(reporting_standards_type='BASIC_4_RETROACTIVE'):
        article.reporting_standards_type = 'BASIC_4_7_RETROACTIVE'
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0055_remove_basic_4_retroactive_article_type'),
    ]

    operations = [
        migrations.RunPython(
            update_reporting_standard,
            migrations.RunPython.noop,
        )
    ]
